name: AIOT-SDAS-Server Pipeline

on:
  push:
    branches:
      - main
    
permissions:
  contents: write

jobs:
  build:
    name: Deploy lastest version of main branch to Render
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions'
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}